// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package platformdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaMigration struct {
	Version   string
	Checksum  string
	AppliedAt pgtype.Timestamptz
}
