// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schema.sql

package platformdb

import (
	"context"
)

const schemaHistory = `-- name: SchemaHistory :many
SELECT version, checksum FROM schema_migrations ORDER BY version
`

type SchemaHistoryRow struct {
	Version  string
	Checksum string
}

func (q *Queries) SchemaHistory(ctx context.Context) ([]SchemaHistoryRow, error) {
	rows, err := q.db.Query(ctx, schemaHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchemaHistoryRow
	for rows.Next() {
		var i SchemaHistoryRow
		if err := rows.Scan(&i.Version, &i.Checksum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
